apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-shared-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-retain
  local:
    path: /srv/k3s-pv-forgejo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - irish-sea

---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-retain
#   labels:
#     type: local
# spec:
#   storageClassName: "local-storage-retain"
#   # storageClassName: ""
#   capacity:
#     storage: 500Mi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   local:
#     path: /srv/k3s-pv-retain
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - irish-sea
