resources:
  - ../base/

patches:
  - target:
      kind: ServiceAccount
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: Role
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: ClusterRole
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: RoleBinding
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: ConfigMap
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard

  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: tekton-deshboard
