apiVersion: operator.tekton.dev/v1alpha1
kind: TektonPruner
metadata:
  name: global-pruner
spec:
  targetNamespace: tekton-pipelines
  disabled: false
  global-config:
    enforcedConfigLevel: global
    historyLimit: 100
    ttlSecondsAfterFinished: 3600
    successfulHistoryLimit: 50
    failedHistoryLimit: 20
