---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-deshboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - path: argocd-app-of-apps/cluster/irish-sea/tekton-pipelines-deshboard/manifests
      repoURL: "https://github.com/OlafRadicke/own_dog_food.git"
      targetRevision: main
      ref: values
      kustomize:
        patches:
          - patch: |-
              - op: replace
                path: /metadata/namespace
                value: tekton-deshboard
  destination:
    namespace: tekton-deshboard
    server: https://kubernetes.default.svc
  project: tekton-deshboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
