---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - path: charts/tekton-operator
      repoURL: https://github.com/tektoncd/operator.git
      targetRevision: v0.78.1
      helm:
        valueFiles:
          - $values/argocd-app-of-apps/cluster/irish-sea/tekton-operator/values.yaml
    - repoURL: "https://github.com/OlafRadicke/own_dog_food.git"
      targetRevision: main
      ref: values

    - path: "stable/release.yaml"
      repoURL: "https://raw.githubusercontent.com/openshift-pipelines/pipelines-as-code/"
      targetRevision: HEAD

  destination:
    namespace: tekton-operator
    server: https://kubernetes.default.svc
  project: tekton-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
