apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: forgejo-http-forgejo
  namespace: pipelines-as-code
spec:
  concurrency_limit: 1
  git_provider:
    type: gitea
    url: http://forgejo-http.forgejo:3000/
    apiurl: http://forgejo-http.forgejo:3000/api/v1
    secret:
      name: pac-git-token-forgejo
      key: token
    webhook_secret:
      name: pac-webhook-secret
      key: webhook-secret
  url: http://forgejo-http.forgejo:3000/gitea_admin/teckton-pac-test
