---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker-ci
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - path: .
      repoURL: oci://ghcr.io/woodpecker-ci/helm/woodpecker
      targetRevision: 3.4.2
      helm:
        valueFiles:
          - $values/argocd-app-of-apps/cluster/irish-sea/woodpecker-ci/values.yaml
    - repoURL: "https://github.com/OlafRadicke/own_dog_food.git"
      targetRevision: main
      ref: values

  destination:
    namespace: woodpecker-ci
    server: https://kubernetes.default.svc
  project: woodpecker-ci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
